# Generated by Django 2.2.1 on 2019-05-20 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Title'),
        ),
    ]
