# Generated by Django 2.2.1 on 2019-05-30 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190520_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
    ]
